import time, json
from util.validate_ai_response import validate_response

async def get_ai_response(messages, model, async_client, hosting: str = "local", timeout: float = 15.0):
    start = time.perf_counter()
    response = await async_client.chat.completions.create(
            model=model,
            messages=messages,
            temperature=0.0,
            max_tokens=300,
            timeout=timeout,
            response_format={
                'type': 'json_object'
                }
        )
    elapsed = time.perf_counter() - start
    print(f"Response generated by {hosting} LLM in {elapsed:.2f} seconds")
    ai_response = json.loads(response.choices[0].message.content)
    if validate_response(ai_response):
        # print(f"VALID RESPONSE BELOW:")
        print(json.dumps(ai_response, indent=4))
        return ai_response
    else:
        print(f"Response is invalid, kindly try again")
        exit()